import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Lato } from "next/font/google";
import TabsButton from "@/components/macro/tabsButton";
import TabsInbox from "@/components/macro/tabsInbox";
import { useState } from "react";
import { Transition } from "@headlessui/react";

const lato = Lato({ subsets: ["latin"], weight: ["300", "100"] });

export default function Home() {
  const [openedTabs, setOpenedTabs] = useState<"main" | "inbox" | "task">(
    "main"
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${styles.mainBox} ${lato.className}`}>
        <div className={styles.firstBox}></div>
        <div className={styles.secondBox}>
          <svg
            width='16'
            height='16'
            viewBox='0 0 16 16'
            fill='none'
            xmlns='http://www.w3.org/2000/svg'>
            <path
              fillRule='evenodd'
              clipRule='evenodd'
              d='M10.7124 10.0629H11.4351L16 14.6369L14.6369 16L10.0629 11.4351V10.7124L9.81589 10.4563C8.77301 11.3528 7.4191 11.8925 5.94625 11.8925C2.66209 11.8925 0 9.23042 0 5.94625C0 2.66209 2.66209 0 5.94625 0C9.23042 0 11.8925 2.66209 11.8925 5.94625C11.8925 7.4191 11.3528 8.77301 10.4563 9.81589L10.7124 10.0629ZM1.82959 5.94554C1.82959 8.22342 3.66835 10.0622 5.94623 10.0622C8.2241 10.0622 10.0629 8.22342 10.0629 5.94554C10.0629 3.66767 8.2241 1.82891 5.94623 1.82891C3.66835 1.82891 1.82959 3.66767 1.82959 5.94554Z'
              fill='#F2F2F2'
            />
          </svg>
          <input type='text' className={styles.secondBoxInput} />
        </div>
        <TabsButton setOpenedTabs={setOpenedTabs} openedTabs={openedTabs} />
        <Transition
          show={openedTabs === "inbox"}
          enter='transition-opacity duration-75'
          enterFrom='opacity-0'
          enterTo='opacity-100'
          leave='transition-opacity duration-150'
          leaveFrom='opacity-100'
          leaveTo='opacity-0'>
          <TabsInbox setIsOpen={setOpenedTabs} />
        </Transition>
        {openedTabs}
      </main>
    </>
  );
}
